# localhost version
server:
  port: 0 # eureka server에 의해서 임의적인 port가 할당됨

# eureka 설정
eureka: 
  client:
    serviceUrl: # eureke 서버에 등록
      defaultZone: http://localhost:8761/eureka

spring:
  rabbitmq: 
  host: localhost
  port: 5672
  username: guest
  password: guest
  
  # mariadb settings
  datasource:
    # 접근하고 싶은 벤더사
    driver-class-name: org.mariadb.jdbc.Driver 
    # db접근하는 경로
    url: jdbc:mariadb://localhost:3306/inspire   # 마지막은 DB 이름
    # 유저정보
    username: root
    password: 123456789

  jpa:
    hibernate: # 테이블 스키마 생성
      # create, create-drop, update, none                                                                  
      ddl-auto: create
    # 콘솔출력
    show-sql: true
    properties:
      hibernate:
      # h2
      # dialect: org.hibernate.dialect.H2Dialect
      # mariadb
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  # redis
  # docker exec -it redis-container redis-cli
  data : 
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 6000ms
  cloud:
    bus:
      enabled: true